package com.amalitech.tib.auth.enums;


public enum Permission{
    FULL_ACCESS,VIEW_LOGS,MANAGE_USERS,MANAGE_ROLES,MANAGE_PERMISSIONS,MANAGE_TRIP,
    MANAGE_ACTIVITY,MANAGE_CATEGORY,MANAGE_ATTRACTION,MANAGE_BUDGET,MANAGE_EXPENSE,
    MANAGE_TRAVELER,MANAGE_TRANSPORT,MANAGE_FEEDBACK,MANAGE_BOOKING, EXPORT_REPORT,
    CREATE_ADMINS, DELETE_ADMINS,DEACTIVATE_ACCOUNT, DELETE_ACCOUNT;
}
